# CMake generated Testfile for 
# Source directory: /home/avengineer/alfred_ws/ros_alfred/src/segbot_navigation
# Build directory: /home/avengineer/alfred_ws/ros_alfred/build/segbot_navigation
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(_ctest_segbot_navigation_roslaunch-check_launch_amcl.launch "/home/avengineer/alfred_ws/ros_alfred/build/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/indigo/share/catkin/cmake/test/run_tests.py" "/home/avengineer/alfred_ws/ros_alfred/build/test_results/segbot_navigation/roslaunch-check_launch_amcl.launch.xml" "--return-code" "/usr/bin/cmake -E make_directory /home/avengineer/alfred_ws/ros_alfred/build/test_results/segbot_navigation" "/opt/ros/indigo/share/roslaunch/cmake/../scripts/roslaunch-check -o '/home/avengineer/alfred_ws/ros_alfred/build/test_results/segbot_navigation/roslaunch-check_launch_amcl.launch.xml' '/home/avengineer/alfred_ws/ros_alfred/src/segbot_navigation/launch/amcl.launch' ")
ADD_TEST(_ctest_segbot_navigation_roslaunch-check_launch_gmapping.launch "/home/avengineer/alfred_ws/ros_alfred/build/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/indigo/share/catkin/cmake/test/run_tests.py" "/home/avengineer/alfred_ws/ros_alfred/build/test_results/segbot_navigation/roslaunch-check_launch_gmapping.launch.xml" "--return-code" "/usr/bin/cmake -E make_directory /home/avengineer/alfred_ws/ros_alfred/build/test_results/segbot_navigation" "/opt/ros/indigo/share/roslaunch/cmake/../scripts/roslaunch-check -o '/home/avengineer/alfred_ws/ros_alfred/build/test_results/segbot_navigation/roslaunch-check_launch_gmapping.launch.xml' '/home/avengineer/alfred_ws/ros_alfred/src/segbot_navigation/launch/gmapping.launch' ")
ADD_TEST(_ctest_segbot_navigation_roslaunch-check_launch_move_base_eband.launch "/home/avengineer/alfred_ws/ros_alfred/build/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/indigo/share/catkin/cmake/test/run_tests.py" "/home/avengineer/alfred_ws/ros_alfred/build/test_results/segbot_navigation/roslaunch-check_launch_move_base_eband.launch.xml" "--return-code" "/usr/bin/cmake -E make_directory /home/avengineer/alfred_ws/ros_alfred/build/test_results/segbot_navigation" "/opt/ros/indigo/share/roslaunch/cmake/../scripts/roslaunch-check -o '/home/avengineer/alfred_ws/ros_alfred/build/test_results/segbot_navigation/roslaunch-check_launch_move_base_eband.launch.xml' '/home/avengineer/alfred_ws/ros_alfred/src/segbot_navigation/launch/move_base_eband.launch' ")
ADD_TEST(_ctest_segbot_navigation_roslaunch-check_launch_rviz.launch "/home/avengineer/alfred_ws/ros_alfred/build/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/indigo/share/catkin/cmake/test/run_tests.py" "/home/avengineer/alfred_ws/ros_alfred/build/test_results/segbot_navigation/roslaunch-check_launch_rviz.launch.xml" "--return-code" "/usr/bin/cmake -E make_directory /home/avengineer/alfred_ws/ros_alfred/build/test_results/segbot_navigation" "/opt/ros/indigo/share/roslaunch/cmake/../scripts/roslaunch-check -o '/home/avengineer/alfred_ws/ros_alfred/build/test_results/segbot_navigation/roslaunch-check_launch_rviz.launch.xml' '/home/avengineer/alfred_ws/ros_alfred/src/segbot_navigation/launch/rviz.launch' ")
