// Generated by gencpp from file alfred_server/ItemResult.msg
// DO NOT EDIT!


#ifndef ALFRED_SERVER_MESSAGE_ITEMRESULT_H
#define ALFRED_SERVER_MESSAGE_ITEMRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace alfred_server
{
template <class ContainerAllocator>
struct ItemResult_
{
  typedef ItemResult_<ContainerAllocator> Type;

  ItemResult_()
    : dispensed(0)
    , error()
    , uid(0)  {
    }
  ItemResult_(const ContainerAllocator& _alloc)
    : dispensed(0)
    , error(_alloc)
    , uid(0)  {
    }



   typedef int8_t _dispensed_type;
  _dispensed_type dispensed;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _error_type;
  _error_type error;

   typedef uint32_t _uid_type;
  _uid_type uid;




  typedef boost::shared_ptr< ::alfred_server::ItemResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::alfred_server::ItemResult_<ContainerAllocator> const> ConstPtr;

}; // struct ItemResult_

typedef ::alfred_server::ItemResult_<std::allocator<void> > ItemResult;

typedef boost::shared_ptr< ::alfred_server::ItemResult > ItemResultPtr;
typedef boost::shared_ptr< ::alfred_server::ItemResult const> ItemResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::alfred_server::ItemResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::alfred_server::ItemResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace alfred_server

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'alfred_server': ['/home/avengineer/alfred_ws/ros_alfred/src/alfred_server/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::alfred_server::ItemResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::alfred_server::ItemResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::alfred_server::ItemResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::alfred_server::ItemResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::alfred_server::ItemResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::alfred_server::ItemResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::alfred_server::ItemResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b07242a1ff28014216fedf5e24fe3ffb";
  }

  static const char* value(const ::alfred_server::ItemResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb07242a1ff280142ULL;
  static const uint64_t static_value2 = 0x16fedf5e24fe3ffbULL;
};

template<class ContainerAllocator>
struct DataType< ::alfred_server::ItemResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "alfred_server/ItemResult";
  }

  static const char* value(const ::alfred_server::ItemResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::alfred_server::ItemResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 dispensed\n\
string error\n\
uint32 uid\n\
";
  }

  static const char* value(const ::alfred_server::ItemResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::alfred_server::ItemResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.dispensed);
      stream.next(m.error);
      stream.next(m.uid);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct ItemResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::alfred_server::ItemResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::alfred_server::ItemResult_<ContainerAllocator>& v)
  {
    s << indent << "dispensed: ";
    Printer<int8_t>::stream(s, indent + "  ", v.dispensed);
    s << indent << "error: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.error);
    s << indent << "uid: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.uid);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ALFRED_SERVER_MESSAGE_ITEMRESULT_H
