(cl:defpackage bwi_msgs-msg
  (:use )
  (:export
   "<AVAILABLEROBOT>"
   "AVAILABLEROBOT"
   "<AVAILABLEROBOTARRAY>"
   "AVAILABLEROBOTARRAY"
   "<STOPBASESTATUS>"
   "STOPBASESTATUS"
   "<LOGICALNAVIGATIONACTIONGOAL>"
   "LOGICALNAVIGATIONACTIONGOAL"
   "<LOGICALNAVIGATIONRESULT>"
   "LOGICALNAVIGATIONRESULT"
   "<LOGICALNAVIGATIONFEEDBACK>"
   "LOGICALNAVIGATIONFEEDBACK"
   "<LOGICALNAVIGATIONACTIONRESULT>"
   "LOGICALNAVIGATIONACTIONRESULT"
   "<LOGICALNAVIGATIONGOAL>"
   "LOGICALNAVIGATIONGOAL"
   "<LOGICALNAVIGATIONACTIONFEEDBACK>"
   "LOGICALNAVIGATIONACTIONFEEDBACK"
   "<LOGICALNAVIGATIONACTION>"
   "LOGICALNAVIGATIONACTION"
  ))

