set(_CATKIN_CURRENT_PACKAGE "rospy")
set(rospy_MAINTAINER "avengineer <avengineer@todo.todo>")
set(rospy_DEPRECATED "")
set(rospy_VERSION "0.0.0")
set(rospy_BUILD_DEPENDS )
set(rospy_RUN_DEPENDS )
set(rospy_BUILDTOOL_DEPENDS "catkin")