set(_CATKIN_CURRENT_PACKAGE "segbot_gazebo")
set(segbot_gazebo_MAINTAINER "Piyush Khandelwal <piyushk@gmail.com>, Jack O'Quin <jack.oquin@gmail.com>")
set(segbot_gazebo_DEPRECATED "")
set(segbot_gazebo_VERSION "0.3.3")
set(segbot_gazebo_BUILD_DEPENDS "roslaunch")
set(segbot_gazebo_RUN_DEPENDS "fake_localization" "gazebo_plugins" "gazebo_ros" "map_server" "rviz" "segbot_bringup" "segbot_description" "segbot_navigation")
set(segbot_gazebo_BUILDTOOL_DEPENDS "catkin")