# CMake generated Testfile for 
# Source directory: /home/avengineer/alfred_ws/ros_alfred/src/segbot_bringup
# Build directory: /home/avengineer/alfred_ws/ros_alfred/build/segbot_bringup
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(_ctest_segbot_bringup_roslaunch-check_launch_includes "/home/avengineer/alfred_ws/ros_alfred/build/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/indigo/share/catkin/cmake/test/run_tests.py" "/home/avengineer/alfred_ws/ros_alfred/build/test_results/segbot_bringup/roslaunch-check_launch_includes.xml" "--return-code" "/usr/bin/cmake -E make_directory /home/avengineer/alfred_ws/ros_alfred/build/test_results/segbot_bringup" "/opt/ros/indigo/share/roslaunch/cmake/../scripts/roslaunch-check -o '/home/avengineer/alfred_ws/ros_alfred/build/test_results/segbot_bringup/roslaunch-check_launch_includes.xml' '/home/avengineer/alfred_ws/ros_alfred/src/segbot_bringup/launch/includes' ")
ADD_TEST(_ctest_segbot_bringup_roslaunch-check_launch_segbot_v1.launch "/home/avengineer/alfred_ws/ros_alfred/build/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/indigo/share/catkin/cmake/test/run_tests.py" "/home/avengineer/alfred_ws/ros_alfred/build/test_results/segbot_bringup/roslaunch-check_launch_segbot_v1.launch.xml" "--return-code" "/usr/bin/cmake -E make_directory /home/avengineer/alfred_ws/ros_alfred/build/test_results/segbot_bringup" "/opt/ros/indigo/share/roslaunch/cmake/../scripts/roslaunch-check -o '/home/avengineer/alfred_ws/ros_alfred/build/test_results/segbot_bringup/roslaunch-check_launch_segbot_v1.launch.xml' '/home/avengineer/alfred_ws/ros_alfred/src/segbot_bringup/launch/segbot_v1.launch' ")
ADD_TEST(_ctest_segbot_bringup_roslaunch-check_launch_segbot_v2.launch "/home/avengineer/alfred_ws/ros_alfred/build/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/indigo/share/catkin/cmake/test/run_tests.py" "/home/avengineer/alfred_ws/ros_alfred/build/test_results/segbot_bringup/roslaunch-check_launch_segbot_v2.launch.xml" "--return-code" "/usr/bin/cmake -E make_directory /home/avengineer/alfred_ws/ros_alfred/build/test_results/segbot_bringup" "/opt/ros/indigo/share/roslaunch/cmake/../scripts/roslaunch-check -o '/home/avengineer/alfred_ws/ros_alfred/build/test_results/segbot_bringup/roslaunch-check_launch_segbot_v2.launch.xml' '/home/avengineer/alfred_ws/ros_alfred/src/segbot_bringup/launch/segbot_v2.launch' ")
ADD_TEST(_ctest_segbot_bringup_roslaunch-check_launch_includes_auxiliary.segbot_v1.hokuyo_only.launch.xml "/home/avengineer/alfred_ws/ros_alfred/build/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/indigo/share/catkin/cmake/test/run_tests.py" "/home/avengineer/alfred_ws/ros_alfred/build/test_results/segbot_bringup/roslaunch-check_launch_includes_auxiliary.segbot_v1.hokuyo_only.launch.xml.xml" "--return-code" "/usr/bin/cmake -E make_directory /home/avengineer/alfred_ws/ros_alfred/build/test_results/segbot_bringup" "/opt/ros/indigo/share/roslaunch/cmake/../scripts/roslaunch-check -o '/home/avengineer/alfred_ws/ros_alfred/build/test_results/segbot_bringup/roslaunch-check_launch_includes_auxiliary.segbot_v1.hokuyo_only.launch.xml.xml' '/home/avengineer/alfred_ws/ros_alfred/src/segbot_bringup/launch/includes/auxiliary.segbot_v1.hokuyo_only.launch.xml' ")
ADD_TEST(_ctest_segbot_bringup_roslaunch-check_launch_includes_auxiliary.segbot_v1.no_sensors.launch.xml "/home/avengineer/alfred_ws/ros_alfred/build/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/indigo/share/catkin/cmake/test/run_tests.py" "/home/avengineer/alfred_ws/ros_alfred/build/test_results/segbot_bringup/roslaunch-check_launch_includes_auxiliary.segbot_v1.no_sensors.launch.xml.xml" "--return-code" "/usr/bin/cmake -E make_directory /home/avengineer/alfred_ws/ros_alfred/build/test_results/segbot_bringup" "/opt/ros/indigo/share/roslaunch/cmake/../scripts/roslaunch-check -o '/home/avengineer/alfred_ws/ros_alfred/build/test_results/segbot_bringup/roslaunch-check_launch_includes_auxiliary.segbot_v1.no_sensors.launch.xml.xml' '/home/avengineer/alfred_ws/ros_alfred/src/segbot_bringup/launch/includes/auxiliary.segbot_v1.no_sensors.launch.xml' ")
ADD_TEST(_ctest_segbot_bringup_roslaunch-check_launch_segway_base.launch "/home/avengineer/alfred_ws/ros_alfred/build/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/indigo/share/catkin/cmake/test/run_tests.py" "/home/avengineer/alfred_ws/ros_alfred/build/test_results/segbot_bringup/roslaunch-check_launch_segway_base.launch.xml" "--return-code" "/usr/bin/cmake -E make_directory /home/avengineer/alfred_ws/ros_alfred/build/test_results/segbot_bringup" "/opt/ros/indigo/share/roslaunch/cmake/../scripts/roslaunch-check -o '/home/avengineer/alfred_ws/ros_alfred/build/test_results/segbot_bringup/roslaunch-check_launch_segway_base.launch.xml' '/home/avengineer/alfred_ws/ros_alfred/src/segbot_bringup/launch/segway_base.launch' ")
