# CMake generated Testfile for 
# Source directory: /home/avengineer/alfred_ws/ros_alfred/src/segbot_sensors
# Build directory: /home/avengineer/alfred_ws/ros_alfred/build/segbot_sensors
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(_ctest_segbot_sensors_roslaunch-check_launch "/home/avengineer/alfred_ws/ros_alfred/build/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/indigo/share/catkin/cmake/test/run_tests.py" "/home/avengineer/alfred_ws/ros_alfred/build/test_results/segbot_sensors/roslaunch-check_launch.xml" "--return-code" "/usr/bin/cmake -E make_directory /home/avengineer/alfred_ws/ros_alfred/build/test_results/segbot_sensors" "/opt/ros/indigo/share/roslaunch/cmake/../scripts/roslaunch-check -o '/home/avengineer/alfred_ws/ros_alfred/build/test_results/segbot_sensors/roslaunch-check_launch.xml' '/home/avengineer/alfred_ws/ros_alfred/src/segbot_sensors/launch' ")
ADD_TEST(_ctest_segbot_sensors_roslaunch-check_launch_arduino "/home/avengineer/alfred_ws/ros_alfred/build/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/indigo/share/catkin/cmake/test/run_tests.py" "/home/avengineer/alfred_ws/ros_alfred/build/test_results/segbot_sensors/roslaunch-check_launch_arduino.xml" "--return-code" "/usr/bin/cmake -E make_directory /home/avengineer/alfred_ws/ros_alfred/build/test_results/segbot_sensors" "/opt/ros/indigo/share/roslaunch/cmake/../scripts/roslaunch-check -o '/home/avengineer/alfred_ws/ros_alfred/build/test_results/segbot_sensors/roslaunch-check_launch_arduino.xml' '/home/avengineer/alfred_ws/ros_alfred/src/segbot_sensors/launch/arduino' ")
ADD_TEST(_ctest_segbot_sensors_roslaunch-check_launch_diagnostic "/home/avengineer/alfred_ws/ros_alfred/build/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/indigo/share/catkin/cmake/test/run_tests.py" "/home/avengineer/alfred_ws/ros_alfred/build/test_results/segbot_sensors/roslaunch-check_launch_diagnostic.xml" "--return-code" "/usr/bin/cmake -E make_directory /home/avengineer/alfred_ws/ros_alfred/build/test_results/segbot_sensors" "/opt/ros/indigo/share/roslaunch/cmake/../scripts/roslaunch-check -o '/home/avengineer/alfred_ws/ros_alfred/build/test_results/segbot_sensors/roslaunch-check_launch_diagnostic.xml' '/home/avengineer/alfred_ws/ros_alfred/src/segbot_sensors/launch/diagnostic' ")
ADD_TEST(_ctest_segbot_sensors_roslaunch-check_launch_hokuyo "/home/avengineer/alfred_ws/ros_alfred/build/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/indigo/share/catkin/cmake/test/run_tests.py" "/home/avengineer/alfred_ws/ros_alfred/build/test_results/segbot_sensors/roslaunch-check_launch_hokuyo.xml" "--return-code" "/usr/bin/cmake -E make_directory /home/avengineer/alfred_ws/ros_alfred/build/test_results/segbot_sensors" "/opt/ros/indigo/share/roslaunch/cmake/../scripts/roslaunch-check -o '/home/avengineer/alfred_ws/ros_alfred/build/test_results/segbot_sensors/roslaunch-check_launch_hokuyo.xml' '/home/avengineer/alfred_ws/ros_alfred/src/segbot_sensors/launch/hokuyo' ")
ADD_TEST(_ctest_segbot_sensors_roslaunch-check_launch_kinect "/home/avengineer/alfred_ws/ros_alfred/build/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/indigo/share/catkin/cmake/test/run_tests.py" "/home/avengineer/alfred_ws/ros_alfred/build/test_results/segbot_sensors/roslaunch-check_launch_kinect.xml" "--return-code" "/usr/bin/cmake -E make_directory /home/avengineer/alfred_ws/ros_alfred/build/test_results/segbot_sensors" "/opt/ros/indigo/share/roslaunch/cmake/../scripts/roslaunch-check -o '/home/avengineer/alfred_ws/ros_alfred/build/test_results/segbot_sensors/roslaunch-check_launch_kinect.xml' '/home/avengineer/alfred_ws/ros_alfred/src/segbot_sensors/launch/kinect' ")
ADD_TEST(_ctest_segbot_sensors_roslaunch-check_launch_ptgrey "/home/avengineer/alfred_ws/ros_alfred/build/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/indigo/share/catkin/cmake/test/run_tests.py" "/home/avengineer/alfred_ws/ros_alfred/build/test_results/segbot_sensors/roslaunch-check_launch_ptgrey.xml" "--return-code" "/usr/bin/cmake -E make_directory /home/avengineer/alfred_ws/ros_alfred/build/test_results/segbot_sensors" "/opt/ros/indigo/share/roslaunch/cmake/../scripts/roslaunch-check -o '/home/avengineer/alfred_ws/ros_alfred/build/test_results/segbot_sensors/roslaunch-check_launch_ptgrey.xml' '/home/avengineer/alfred_ws/ros_alfred/src/segbot_sensors/launch/ptgrey' ")
SUBDIRS(src/sonar)
