set(_CATKIN_CURRENT_PACKAGE "segbot_navigation")
set(segbot_navigation_RUN_DEPENDS_move_base_VERSION_GTE "1.11.15")
set(segbot_navigation_VERSION "0.3.3")
set(segbot_navigation_MAINTAINER "Piyush Khandelwal <piyushk@gmail.com>, Jack O'Quin <jack.oquin@gmail.com>")
set(segbot_navigation_BUILD_DEPENDS "bwi_interruptable_action_server" "geometry_msgs" "move_base_msgs" "nav_msgs" "std_srvs" "roslaunch")
set(segbot_navigation_RUN_DEPENDS "bwi_interruptable_action_server" "geometry_msgs" "move_base_msgs" "nav_msgs" "std_srvs" "amcl" "eband_local_planner" "gmapping" "map_server" "move_base" "navfn" "rviz" "segbot_bringup")
set(segbot_navigation_DEPRECATED "")
set(segbot_navigation_BUILDTOOL_DEPENDS "catkin")