(cl:defpackage bwi_msgs-srv
  (:use )
  (:export
   "DOORHANDLERINTERFACE"
   "<DOORHANDLERINTERFACE-REQUEST>"
   "DOORHANDLERINTERFACE-REQUEST"
   "<DOORHANDLERINTERFACE-RESPONSE>"
   "DOORHANDLERINTERFACE-RESPONSE"
   "QUESTIONDIALOG"
   "<QUESTIONDIALOG-REQUEST>"
   "QUESTIONDIALOG-REQUEST"
   "<QUESTIONDIALOG-RESPONSE>"
   "QUESTIONDIALOG-RESPONSE"
   "SEMANTICPARSER"
   "<SEMANTICPARSER-REQUEST>"
   "SEMANTICPARSER-REQUEST"
   "<SEMANTICPARSER-RESPONSE>"
   "SEMANTICPARSER-RESPONSE"
   "STOPBASE"
   "<STOPBASE-REQUEST>"
   "STOPBASE-REQUEST"
   "<STOPBASE-RESPONSE>"
   "STOPBASE-RESPONSE"
  ))

