set(_CATKIN_CURRENT_PACKAGE "alfred_server")
set(alfred_server_MAINTAINER "avengineer <avengineer@todo.todo>")
set(alfred_server_DEPRECATED "")
set(alfred_server_VERSION "0.0.0")
set(alfred_server_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(alfred_server_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(alfred_server_BUILDTOOL_DEPENDS "catkin")